FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o serveur ./cmd/server

FROM alpine:3.18

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/serveur /serveur

RUN mkdir /share

EXPOSE 8080

CMD ["/serveur"]
