FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o {{.ServiceName}} ./cmd/{{.ServiceName}}

FROM alpine:latest

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/{{.ServiceName}} /{{.ServiceName}}

RUN mkdir /share

EXPOSE 8080

CMD ["/{{.ServiceName}}"]
